knp_gaufrette:
  stream_wrapper: ~

  adapters:
    author_adapter:
      local:
        directory: "%kernel.project_dir%/public/images/authors"

  filesystems:
    author_fs:
      adapter: author_adapter

vich_uploader:
  db_driver: orm
  storage: gaufrette

  metadata:
    type: attribute

  mappings:
    authors:
      uri_prefix: /images/authors
      upload_destination: author_fs
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      inject_on_load: false
      delete_on_remove: true
      delete_on_update: true
