knp_gaufrette:
  stream_wrapper: ~

  adapters:
    author_adapter:
      local:
        directory: "%kernel.project_dir%/public/images/authors"

    bookImage_adapter:
      local:
        directory: "%kernel.project_dir%/public/images/bookImages"

  filesystems:
    author_fs:
      adapter: author_adapter
    bookImage_fs:
      adapter: bookImage_adapter

vich_uploader:
  db_driver: orm
  storage: gaufrette

  metadata:
    type: attribute

  mappings:
    authors:
      uri_prefix: /images/authors
      upload_destination: author_fs
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      inject_on_load: true
      delete_on_remove: true
      delete_on_update: true
    bookImages:
      uri_prefix: /images/bookImages
      upload_destination: bookImage_fs
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      inject_on_load: true
      delete_on_remove: true
      delete_on_update: true

when@test:
  knp_gaufrette:
    adapters:
      author_adapter:
        local:
          directory: "%kernel.cache_dir%/images/authors"
      bookImage_adapter:
        local:
          directory: "%kernel.cache_dir%/images/bookImages"
